name: Checkov Docker Scan

on:
  workflow_dispatch:
  permissions:
  contents: read
  checks: write
  security-events: write
#push:
 #   branches: [ main ]
  #pull_request:

jobs:
  checkov-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Checkov (v2.1.97)
        run: pip3 install checkov

      - name: Scan docker file
        run: |
          checkov -f Dockerfile --output sarif || true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

      - name: Upload SARIF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: results.sarif
