name: Checkov
on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
        
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: DockerFile
      - name: Upload SARIF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: results.sarif
          
